import { arcMainnet, arcTest } from "@sealedrfq/shared";
import { defineChain } from "viem";
import testnetDeployment from "./deployments/5042002.json";
import localDeployment from "./deployments/local.json";

/** `arc-anvil --network arc`: Arc rules and the USDC precompile on a throwaway chain. */
export const arcLocal = defineChain({
  ...arcTest,
  id: 31337,
  name: "Arc Local",
  rpcUrls: { default: { http: [process.env.NEXT_PUBLIC_ARC_RPC_URL ?? "http://127.0.0.1:8545"] } },
  blockExplorers: { default: { name: "local", url: "http://127.0.0.1:8545" } },
});

/**
 * Which Arc network this build talks to, and where the contracts live on it.
 * Deployment files are generated by contracts/script/Deploy.s.sol.
 */
export const CHAIN_ID = Number(process.env.NEXT_PUBLIC_ARC_CHAIN_ID ?? 5042002);

export const chain =
  CHAIN_ID === arcMainnet.id ? arcMainnet : CHAIN_ID === arcLocal.id ? arcLocal : arcTest;
export const isLocal = CHAIN_ID === arcLocal.id;

type Deployment = {
  chainId: number;
  startBlock: number;
  usdc: `0x${string}`;
  admin: `0x${string}`;
  AgenticCommerce: `0x${string}`;
  AttestationLog: `0x${string}`;
  ProcurementPolicy: `0x${string}`;
  SealedRFQAdapter: `0x${string}`;
  RFQRegistry: `0x${string}`;
};

/**
 * Addresses for the chain this build targets, looked up rather than inferred.
 *
 * This used to be `isLocal ? local : testnet`, which meant pointing the build at mainnet gave it
 * mainnet chain settings and testnet addresses — a wallet on real money calling contracts that do
 * not exist there. A missing deployment must stop the build, not fall back to whichever file
 * happens to be imported. Add the mainnet entry here when contracts/deployments/5042.json exists.
 */
const byChain: Record<number, Deployment> = {
  [arcLocal.id]: localDeployment as Deployment,
  [arcTest.id]: testnetDeployment as Deployment,
};

export const contracts: Deployment = (() => {
  const found = byChain[CHAIN_ID];
  if (!found) {
    throw new Error(
      `No deployment file for chain ${CHAIN_ID}. Deploy it, copy contracts/deployments/${CHAIN_ID}.json into apps/web/lib/deployments/, and register it in lib/chain.ts.`,
    );
  }
  // Catches a file copied from the wrong network as well as a mis-set environment variable.
  if (found.chainId !== CHAIN_ID) {
    throw new Error(
      `Deployment file for chain ${CHAIN_ID} declares chainId ${found.chainId}: the addresses do not belong to this network.`,
    );
  }
  return found;
})();

/**
 * RPC endpoints for this build, best first.
 *
 * Arc's public endpoints share a rate limiter: `rpc.testnet.arc.io`, `rpc.testnet.arc.network` and
 * the QuickNode one all start returning 429 together under load, which a browser reports as the
 * uninformative "HTTP request failed". A single URL is therefore a single point of failure, so
 * these are handed to viem's fallback transport and it moves to the next one on error.
 *
 * NEXT_PUBLIC_ARC_RPC_URL goes first when set. It used to be read only for the local chain, so
 * setting it for a deployment quietly did nothing.
 */
const PUBLIC_RPCS: Record<number, string[]> = {
  5042: [
    "https://rpc.mainnet.arc.io",
    "https://rpc.blockdaemon.mainnet.arc.io",
    "https://rpc.quicknode.mainnet.arc.io",
  ],
  5042002: [
    "https://rpc.blockdaemon.testnet.arc.network",
    "https://rpc.testnet.arc.network",
    "https://rpc.testnet.arc.io",
  ],
  31337: ["http://127.0.0.1:8545"],
};

export const rpcUrls: string[] = [
  ...new Set([
    ...(process.env.NEXT_PUBLIC_ARC_RPC_URL ? [process.env.NEXT_PUBLIC_ARC_RPC_URL] : []),
    ...(PUBLIC_RPCS[CHAIN_ID] ?? chain.rpcUrls.default.http),
  ]),
];

/** Mainnet moves real money and Arc settlement is forward-only: no undo, no chargeback. */
export const isMainnet = CHAIN_ID === arcMainnet.id;

export const explorerTx = (hash: string) => `${chain.blockExplorers.default.url}/tx/${hash}`;
export const explorerAddress = (address: string) =>
  `${chain.blockExplorers.default.url}/address/${address}`;
