import { arcMainnet, arcTest } from "@sealedrfq/shared";
import { defineChain } from "viem";
import localDeployment from "./deployments/local.json";
import testnetDeployment from "./deployments/5042002.json";

/** `arc-anvil --network arc`: Arc rules and the USDC precompile on a throwaway chain. */
export const arcLocal = defineChain({
  ...arcTest,
  id: 31337,
  name: "Arc Local",
  rpcUrls: { default: { http: [process.env.NEXT_PUBLIC_ARC_RPC_URL ?? "http://127.0.0.1:8545"] } },
  blockExplorers: { default: { name: "local", url: "http://127.0.0.1:8545" } },
});

/**
 * Which Arc network this build talks to, and where the contracts live on it.
 * Deployment files are generated by contracts/script/Deploy.s.sol.
 */
export const CHAIN_ID = Number(process.env.NEXT_PUBLIC_ARC_CHAIN_ID ?? 5042002);

export const chain =
  CHAIN_ID === arcMainnet.id ? arcMainnet : CHAIN_ID === arcLocal.id ? arcLocal : arcTest;
export const isLocal = CHAIN_ID === arcLocal.id;

type Deployment = {
  chainId: number;
  startBlock: number;
  usdc: `0x${string}`;
  admin: `0x${string}`;
  AgenticCommerce: `0x${string}`;
  AttestationLog: `0x${string}`;
  ProcurementPolicy: `0x${string}`;
  SealedRFQAdapter: `0x${string}`;
  RFQRegistry: `0x${string}`;
};

// The mainnet file lands on day 18; local is written by tools/local.sh.
export const contracts = (isLocal ? localDeployment : testnetDeployment) as Deployment;

/** Mainnet moves real money and Arc settlement is forward-only: no undo, no chargeback. */
export const isMainnet = CHAIN_ID === arcMainnet.id;

export const explorerTx = (hash: string) => `${chain.blockExplorers.default.url}/tx/${hash}`;
export const explorerAddress = (address: string) =>
  `${chain.blockExplorers.default.url}/address/${address}`;
