import { arcMainnet, arcTest } from "@sealedrfq/shared";
import testnetDeployment from "./deployments/5042002.json";

/**
 * Which Arc network this build talks to, and where the contracts live on it.
 * Deployment files are generated by contracts/script/Deploy.s.sol.
 */
export const CHAIN_ID = Number(process.env.NEXT_PUBLIC_ARC_CHAIN_ID ?? 5042002);

export const chain = CHAIN_ID === arcMainnet.id ? arcMainnet : arcTest;

type Deployment = {
  chainId: number;
  startBlock: number;
  usdc: `0x${string}`;
  admin: `0x${string}`;
  AgenticCommerce: `0x${string}`;
  AttestationLog: `0x${string}`;
  ProcurementPolicy: `0x${string}`;
  SealedRFQAdapter: `0x${string}`;
  RFQRegistry: `0x${string}`;
};

// Only the testnet deployment exists today; the mainnet file lands on day 18.
export const contracts = testnetDeployment as Deployment;

export const explorerTx = (hash: string) => `${chain.blockExplorers.default.url}/tx/${hash}`;
export const explorerAddress = (address: string) =>
  `${chain.blockExplorers.default.url}/address/${address}`;
