#!/usr/bin/env bash
# Exports the ABIs the agent service and the web app need, from forge artifacts into
# packages/shared/src/abis/. Run after any contract change:  ./script/export-abis.sh
set -euo pipefail
cd "$(dirname "$0")/.."
OUT=../packages/shared/src/abis
mkdir -p "$OUT"

forge build >/dev/null

CONTRACTS="RFQRegistry SealedRFQAdapter AgenticCommerce ProcurementPolicy AttestationLog"

# The ABI is inlined as a TS literal with `as const` (not a JSON import) so viem and wagmi can
# infer argument and return types from it.
for c in $CONTRACTS; do
  # `as const` must sit on the same line as the literal, or ASI ends the statement first.
  {
    echo "// Generated by contracts/script/export-abis.sh - do not edit."
    echo "export const ${c}Abi = $(jq -c '.abi' "out/$c.sol/$c.json") as const;"
  } > "$OUT/$c.ts"
  echo "  $c: $(jq '.abi | length' "out/$c.sol/$c.json") entries"
done

{
  echo "// Generated by contracts/script/export-abis.sh - do not edit."
  for c in $CONTRACTS; do echo "export { ${c}Abi } from \"./${c}.js\";"; done
} > "$OUT/index.ts"

echo "wrote $OUT"
