#!/usr/bin/env bash
# Run the whole stack on a throwaway local Arc chain — no testnet funds, instant transactions,
# and a clock you can fast-forward instead of waiting out bidding and acceptance windows.
#
#   tools/local.sh up        start the chain, deploy, seed, run the agent and the web app
#   tools/local.sh warp 5m   move the chain clock forward (s/m/h/d suffixes)
#   tools/local.sh demo      run the full lifecycle end to end, warping past every window
#   tools/local.sh status    what is running and what is on-chain
#   tools/local.sh down      stop everything
#
# Requires arc-anvil (Arc rules + the USDC precompile; plain anvil cannot move Arc USDC).
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
RPC=${RPC:-http://127.0.0.1:8545}
ENV_FILE="$ROOT/.env.local"
RUN="$ROOT/.local"
mkdir -p "$RUN"

# anvil's standard development accounts: publicly known keys, worthless outside this chain.
# Account #9 (0xa0Ee…9720) is the USDC proxy admin on a local Arc chain and the proxy refuses calls
# from its own admin, so that account is skipped entirely and #10 is used instead.
ADMIN_PK=0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80
EVALUATOR_PK=0x59c6995e998f97a5a0044966f0945389dc9e86dae88c7a8412f4603b6b78690d
AWARDER_PK=0x5de4111afa1a4b94908f83103eb1f1706367c2e68ca870fc3fb9a804cdab365a
VERIFIER_PK=0x7c852118294e51e653712a81e05800f419141751be58f605c371e15141b007a6
ATTESTOR_PK=0x47e179ec197488593b187f80a00eb0da91f1b9d0b13f8733639f19c30a34926a
ARBITER_PK=0x8b3a350cf5c34c9194ca85829a2df0ec3153be0318b5e2d3348e872092edffba
BUYER_PK=0x92db14e403b83dfe3df233f83dfa3a0d7096f21ca9b0d6d6b8d88b2b4ec1564e
SUPPLIER_1_PK=0x4bbbf85ce3377467afe5d46f804f221813b2bb87f24d81f60f1fcdbf7cbf4356
SUPPLIER_2_PK=0xdbda1821b80551c9d65939329250298aa3472ba22feea921c0cf5d620ea67b97
SUPPLIER_3_PK=0xf214f2b2cd398c806f84e317254e0f0b801d0643303237d97a22a48e01628897 # index 10

write_env() {
  cat > "$ENV_FILE" <<EOF
# Generated by tools/local.sh — anvil's public development keys, local chain only.
ARC_RPC_URL=$RPC
ARC_CHAIN_ID=31337
USDC_ADDRESS=0x3600000000000000000000000000000000000000
LLM_PROVIDER=mock
DATABASE_URL=file:./data/local.db
DEPLOYMENT_JSON=$ROOT/contracts/deployments/31337.json
ADMIN_PK=$ADMIN_PK
EVALUATOR_PK=$EVALUATOR_PK
AWARDER_PK=$AWARDER_PK
VERIFIER_PK=$VERIFIER_PK
ATTESTOR_PK=$ATTESTOR_PK
ARBITER_PK=$ARBITER_PK
BUYER_PK=$BUYER_PK
SUPPLIER_1_PK=$SUPPLIER_1_PK
SUPPLIER_2_PK=$SUPPLIER_2_PK
SUPPLIER_3_PK=$SUPPLIER_3_PK
EOF
}

seconds() { # 5m -> 300
  local v=$1
  case "$v" in
    *s) echo "${v%s}" ;;
    *m) echo $(( ${v%m} * 60 )) ;;
    *h) echo $(( ${v%h} * 3600 )) ;;
    *d) echo $(( ${v%d} * 86400 )) ;;
    *) echo "$v" ;;
  esac
}

warp() {
  local secs; secs=$(seconds "${1:-60}")
  cast rpc evm_increaseTime "$secs" --rpc-url "$RPC" >/dev/null
  cast rpc evm_mine --rpc-url "$RPC" >/dev/null
  echo "   chain clock +${secs}s (now $(cast block latest -f timestamp --rpc-url "$RPC"))"
}

# Runs a forge script and prints why it failed rather than dying silently.
run_forge() {
  local name=$1
  if ! (cd "$ROOT/contracts" && arc-forge script "script/$name.s.sol" --rpc-url "$RPC" --broadcast \
        > "$RUN/$name.log" 2>&1); then
    echo "   $name FAILED:"; grep -E "Error|revert|custom error" "$RUN/$name.log" | head -3
    exit 1
  fi
}

wait_rpc() {
  for _ in $(seq 1 40); do cast chain-id --rpc-url "$RPC" >/dev/null 2>&1 && return 0; sleep 0.5; done
  echo "local chain did not start; see $RUN/anvil.log" >&2; exit 1
}

up() {
  command -v arc-anvil >/dev/null || { echo "arc-anvil not found: install Arc Foundry" >&2; exit 1; }
  down >/dev/null 2>&1 || true
  write_env
  set -a; . "$ENV_FILE"; set +a

  echo "── starting a local Arc chain (arc rules, USDC precompile, prefunded accounts)"
  # -b 1: one-second blocks, so time-dependent phases move without manual mining.
  nohup arc-anvil --network arc --port "${RPC##*:}" -b 1 --accounts 12 \
    </dev/null > "$RUN/anvil.log" 2>&1 & disown
  wait_rpc
  echo "   chain $(cast chain-id --rpc-url "$RPC") · $RPC"

  echo "── deploying contracts"
  run_forge Deploy
  run_forge Configure
  cp "$ROOT/contracts/deployments/31337.json" "$ROOT/apps/web/lib/deployments/local.json"
  echo "   registry $(jq -r .RFQRegistry "$ROOT/contracts/deployments/31337.json")"

  echo "── seeding RFQs"
  STAGE=open run_forge SeedLocal
  warp 90   # push the short-clock RFQs into their reveal window
  STAGE=reveal run_forge SeedLocal

  echo "── starting the agent (indexer + evaluator) on :4020"
  (cd "$ROOT/apps/agent" && pnpm build >/dev/null 2>&1)
  (cd "$ROOT/apps/agent" && rm -f data/local.db*)
  (cd "$ROOT/apps/agent" && nohup env PORT=4020 node dist/main.js </dev/null > "$RUN/agent.log" 2>&1 & disown)

  echo "── starting the web app on :3000"
  (cd "$ROOT/apps/web" && nohup env NEXT_PUBLIC_ARC_CHAIN_ID=31337 \
    NEXT_PUBLIC_AGENT_URL=http://127.0.0.1:4020 pnpm dev </dev/null > "$RUN/web.log" 2>&1 & disown)

  cat <<EOF

Local stack is up.

  web    http://localhost:3000
  agent  http://127.0.0.1:4020/health
  chain  $RPC (id 31337)

Connect MetaMask to this chain:
  Network name  Arc Local
  RPC URL       $RPC
  Chain ID      31337
  Currency      USDC

Import an account (each starts with 1,000,000 USDC):
  buyer      $BUYER_PK
  supplier1  $SUPPLIER_1_PK
  supplier2  $SUPPLIER_2_PK

Windows are real time, so skip them instead of waiting:
  tools/local.sh warp 5m      # past a bidding, reveal or acceptance window
  tools/local.sh demo         # the whole lifecycle, warping as it goes
EOF
}

demo() {
  set -a; . "$ENV_FILE"; set +a
  (cd "$ROOT/contracts" && NET=local RPC_URL="$RPC" BID_SECS=60 REVEAL_SECS=60 AWARD_SECS=3600 \
    DELIVERY_SECS=900 ACCEPT_SECS=120 ./script/demo.sh local)
}

status() {
  echo "chain:  $(cast chain-id --rpc-url "$RPC" 2>/dev/null || echo 'not running')"
  echo "agent:  $(curl -sf http://127.0.0.1:4020/health 2>/dev/null || echo 'not running')"
  echo "web:    $(curl -sf -o /dev/null -w '%{http_code}' http://localhost:3000 2>/dev/null || echo 'not running')"
  if [ -f "$ROOT/contracts/deployments/31337.json" ]; then
    local reg; reg=$(jq -r .RFQRegistry "$ROOT/contracts/deployments/31337.json")
    echo "rfqs:   $(cast call "$reg" 'rfqCount()(uint256)' --rpc-url "$RPC" 2>/dev/null || echo '-')"
  fi
}

down() {
  pkill -f "arc-anvil --network arc" || true
  pkill -f "apps/agent/dist/main.js" || true
  pkill -f "node dist/main.js" || true
  pkill -f "next dev" || true
  echo "stopped"
}

case "${1:-up}" in
  up) up ;;
  warp) warp "${2:-60}" ;;
  demo) demo ;;
  status) status ;;
  down) down ;;
  *) echo "usage: tools/local.sh [up|warp <5m>|demo|status|down]" >&2; exit 1 ;;
esac
